Basic instrutions for compiling / cross-compiling
redlab-i/pps-tools pull request #14
Opened 2021-11-19 15:15 UTC by robamu

2021-11-20 10:50 UTC, gerasiov requested changes

2021-11-20 10:50 UTC, gerasiov commented on README.md
> +You can read more about LinuxPPS [here](http://linuxpps.org/doku.php)
```(http://linuxpps.org)``` should be better i believe

2021-11-21 18:40 UTC, robamu commented on README.md
> +You can read more about LinuxPPS [here](http://linuxpps.org/doku.php)
corrected

2021-11-22 07:48 UTC, gerasiov approved these changes

2021-11-22 07:48 UTC, merged